version: '3.7'

services:
  database_ignite:
    image: bitnami/postgresql:latest
    container_name: db_rentx
    #ports:
    #  - 5432:5432
    #restart: always
    environment:
      - POSTGRESQL_USERNAME=rentx
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DATABASE=rentx
      - POSTGRESQL_POSTGRES_PASSWORD=rentx
    volumes:
      - postgresql_data:/bitnami/postgresql
    network_mode: host
  app:
    build: .
    container_name: rentx
    #ports:
    #  - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  postgresql_data:
    driver: local
